spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/session/jdbc/schema-h2.sql
      # Fixes "Table SPRING_SESSION already exists" in IntelliJ IDEA tests due to context reuse
      continue-on-error: true
  datasource:
    url: jdbc:h2:mem:default
    username: postgres
    password: af15be37-f9dd-4418-b219-19559fc31bff
