server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always
  servlet:
    encoding:
      force: true
    session:
      timeout: 7d

logging:
  level:
    ru.virgil: INFO
    org:
      springframework: WARN

spring:
  profiles: # H2 and Postgres configs are in separate config files
    active: h2
  config:
    import: optional:classpath:credentials/credentials.yaml
  output:
    ansi:
      enabled: always
  security: # credentials are in resources/credentials/credentials.yaml
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

security:
  cors:
    origins: http://localhost:8080
    exposed-headers: X-Auth-Token
    allow-credentials: true
  anonymous-paths:
    - "/actuator/**"
    - "/image/public/**"
    - "/ping"
    - "/"

images:
  clean-on-shutdown: true

web-socket:
  allow-auth-uri-query-parameter: true
  enabled: true
  public-destinations:
    - "/chat"
