spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/session/jdbc/schema-h2.sql
  datasource:
    url: jdbc:h2:mem:default
    username: postgres
    password: af15be37-f9dd-4418-b219-19559fc31bff
