services:

  spring-module-app:
    image: 'spring-module-example:0.0.1-SNAPSHOT'
    build:
      context: .
    container_name: spring-module-app
    user: "${UID}:${GID}"
    depends_on:
      - spring-module-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://spring-module-db:5432/postgres
    ports:
      - 8080:8080
    volumes:
      - image-data:/workspace/image

  spring-module-db:
    image: 'postgres:latest'
    container_name: spring-module-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=af15be37-f9dd-4418-b219-19559fc31bff
    ports:
      - 5432:5432

volumes:
  image-data:
